name: frontend
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc.js'
      - 'tsconfig.json'
  pull_request:
    paths:
      - 'webapp/**'
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc.js'
      - 'tsconfig.json'

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "frontend-${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Run type-check
        run: yarn type-check
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Run format
        run: yarn run format
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Run lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Run build
        run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
